import type { Metadata } from "next";
import { Manrope, Racing_Sans_One } from "next/font/google";
import "./globals.css";
import AuthProvider from "./provider/AuthProvider";
import AppProvider from "./provider/AppProvider";

// ✅ Manrope setup (body font)
const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const racingSansOne = Racing_Sans_One({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: "400", // only one weight allowed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${racingSansOne.variable} antialiased`}
      >
        <AppProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </AppProvider>
      </body>
    </html>
  );
}
